### ISSUE TITLE
Use control/alt/shift keys on element.invoke

### ISSUE THREAD

**Issue by danhi** [Roemer/FlaUI#102]
I have a button that exhibits different behavior based on whether some combination of control/alt/shift keys are held down when it's clicked.  Is this possible to emulate with FlaUI?

**Comment by Roemer** [comment]
See: https://github.com/Roemer/FlaUI/wiki/Keyboard

So in your example:
```csharp
using (Keyboard.Pressing(VirtualKeyShort.ALT))
{
    myElement.Click();
}
```

**Comment by danhi** [comment]
So I tried

                                Using Keyboard.Pressing(VirtualKeyShort.ALT Or VirtualKeyShort.CONTROL)
                                    mnuWriteButton.Click()
                                End Using
and also using an AND instead of an OR for the virtualkeys, and it still just acts like I clicked the write button without holding down any keys.

**Comment by Roemer** [comment]
You can't use them like flags. You should use two `using` with each key separate.

**Comment by danhi** [comment]
I'm not that familiar with using clauses, but doing some reading it appears to be for handling items with IDisposable interfaces so that they are disposed of when no longer needed.  Do it perform some other action here?

**Comment by Roemer** [comment]
The using just disposes the object created in the using statement when it is getting out of scope.
The object I return here presses the given key on creation and releases them on disposing.
The problem here is that you add/or (boolean operation) the keys together which does not work as they are not flags (flags are e.g 1,2,4,8, ... so that every flag value is always unique even when adding / oring them toghether, but here there are 1,2,3,4,5, ... so if you "and" 2 and 3 together you get 5 instead of 2 and 3).

**Comment by Roemer** [comment]
I might add an overload where you can pass an array of keys for multiple.

**Comment by danhi** [comment]
That did it, thanks.
