### ISSUE TITLE
Cannot find input in inspection

### ISSUE THREAD

**Issue by marcelo-maciel** [Roemer/FlaUI#136]
Hi Guys!

I have listitems with checkbox inside, and i need to check one by one and do another process (#133), but i cannot find the checkbox in inspection, like image below.
Are there any way to find the checkbox? How would you solve this?

![image](https://user-images.githubusercontent.com/4993482/35371322-8edd8382-017a-11e8-8c0c-b2fe3327ef23.png)

**Comment by Roemer** [comment]
I guess this is either a WinForms application (WinForms does not provide the checkbox inside a list) or the control is manually build but not provided to UIA. There is an invoke pattern, what happens if you use that and call `Invoke`?
If you just need to check the checkbox you can simply use the `Mouse` class and click on the checkbox by using some math.
This application seems to be built very badly for UIA and Accessibility.

**Comment by marcelo-maciel** [comment]
Thanks @Roemer!
I tried decompile, to see what's the problem, but it's not .NET application, then I will do your sugestion and use mouse with coordenates.
But I not understand this part:
"There is an invoke pattern, what happens if you use that and call Invoke?"
How I will use invoke if i cannot select the object?

**Comment by Roemer** [comment]
The list item directly contains the invoke pattern (the selected item in your screenshot). Maybe invoking that somehow toggles the checkbox?
If it's not .net, have you tried UIA2? Maybe that can show more in this case.

**Comment by marcelo-maciel** [comment]
No, unfortunately that not toggle the checkbox. :(
Yes, i tried UIA2, but the same pattern occurs.
I finished this with clicking with the mouse, thanks for the help @Roemer!
