### ISSUE TITLE
Tool Tip Support for FlaUI

### ISSUE THREAD

**Issue by harrizhasan84** [Roemer/FlaUI#154]
Does FlaUI has support to read Tool Tip Text on Mouse Hover?

**Comment by Roemer** [comment]
Yes. Although it can be difficult to find the tooltip element because it mostly only exists while the tooltip is visible and disappers when you change focus. So either try to make it permanent for a few seconds or use FlaUInspect with the Hover Mode or the Focus Mode to find the element so you know the path to it.

**Comment by harrizhasan84** [comment]
Thanks, This worked.
