### ISSUE TITLE
System.InvalidOperationException: 'Process has exited, so the requested information is not available.'

### ISSUE THREAD

**Issue by guiflaui** [Roemer/FlaUI#183]
System.InvalidOperationException: 'Process has exited, so the requested information is not available.'

When I run the code below in visual studio 2017 and windows 10 pro, I got the above error, please help.

```csharp
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using FlaUI.Core.AutomationElements;
using FlaUI.Core.Input;
using FlaUI.Core.WindowsAPI;
using FlaUI.UIA3;

namespace testclick
{
    class Program
    {
        static void Main(string[] args)
        {
            var app = FlaUI.Core.Application.Launch("C:\\Windows\\System32\\calc.exe");
            using (var automation = new UIA3Automation())
            {
                var window = app.GetMainWindow(automation);
                var button1 = window.FindFirstDescendant(cf => cf.ByText("1"))?.AsButton();
                button1?.Invoke();
            }
        }
    }
}
```

**Comment by Roemer** [comment]
`calc.exe` on Windows 10 is just some kind of shim which starts the Windows Store App Calculator and immediately closes itself afterwards. That's why you get that exception.
Have a look at https://github.com/Roemer/FlaUI/blob/master/src/FlaUI.Core.UITests/CalculatorTests.cs on how to use the Windows Store calculator in FlaUI.

**Comment by guiflaui** [comment]
thanks for explanation
