### ISSUE TITLE
FLAUI Impact on test application performance

### ISSUE THREAD

**Issue by ASIEngineer** [Roemer/FlaUI#188]
Do you have any data on the performance impact FLAUI has on an application you would be performing UI automation tests on?  any benchmark testing, etc.?

I really like FLAUI but some other engineers have concern that manipulating application UI using it in UI automation testing might have real performance ramifications on the app under test.

**Comment by Roemer** [comment]
Since FlaUI uses the Windows Automation API (which is also used for Accessibility) there is no `overhead` on the application under test. Some control libraries (like DevExpress) disable some Accessibility/Automation features by default which need to be enabled in order to fully automate an application. So Accessibility/Automation can have some impact but that has nothing to do with FlaUI.
