### ISSUE TITLE
Should I use WinAppDriver or FlaUI?

### ISSUE THREAD

**Issue by lanzorg** [Roemer/FlaUI#226]
FlaUI is "still" not working with DotNetCore and WinAppDriver is supported by Microsoft.  
Does it mean I should switch to WinAppDriver or I missed something?

**Comment by godrose** [comment]
@lanzorg. Good point

**Comment by yawnston** [comment]
WinAppDriver requires Windows 10, which is quite a big restriction.

**Comment by miloszkukla** [comment]
WinAppDriver has its drawbacks. Technically WinAppDriver is http-accessible abstraction over UIAutomation library. Being closed source means there is little to nothing we can do to modify its behavior like we can with FluUI/AutomationElement direct access. Http adds additional layer of indirection which may not be desired in some scenarios (e.g. where automation performance matters - it would interesting to see some statistics though).

**Comment by daluu** [comment]
On the HTTP layer addition for WinAppDriver, I wonder if that matters much from a performance and complexity viewpoint. On the performance viewpoint, I wonder how critical that is for most users, it's probably more for high performance UI applications like graphics heavy processing (video, gaming, high res photography viewing/editing) where you want the automation to run speedily or are doing timing benchmarks using UI automation or where lags from UI automation could cause test glitches.

The HTTP layer model is standard for Selenium WebDriver for browsers and Appium for mobile. If I'm not mistaken, but I might stand corrected, even for native driver implementation for Selenium where a remote Server (JAR) is not required to be running,  they're based on the JSONWireProtocol, so it still goes through the HTTP abstraction. They seem reliable enough (although not perfect), and in most cases is still pretty speedy in execution.

**Comment by bkilada** [comment]
Wanted to chime in on this because I've been attempting to write a GUI stress test for a complex win forms app with hosted WPF controls and found WinAppDriver to be extremely slow when querying by XPath. Painfully, unusable slow. The APIs are also fairly limited compared to FlaUI, definitely have had a much smoother experience so far with this tool.

For example, it is extremely easy to get all the child elements of a parent element in FlaUI, wheras in Appium with WinAppDriver I had to write some custom code to create my own XPath, which, as I mentioned above, is too slow to use anyway. I see the potential in WinAppDriver, but it seems like it's not quite ready for prime-time yet. It might work great if you're making a simple app, or perhaps if you're searching by properties such as name or automation id for individual controls instead of trying to make a crazy stress test like me.

See [https://github.com/Microsoft/WinAppDriver/issues/669](https://github.com/Microsoft/WinAppDriver/issues/669).

**Comment by daluu** [comment]
@bkilada it might also be interesting to see how using other tools compare for your GUI automation use case for tools like TestStack White and direct use of UIAutomation.

**Comment by jakubsuchybio** [comment]
> Wanted to chime in on this because I've been attempting to write a GUI stress test for a complex win forms app with hosted WPF controls and found WinAppDriver to be extremely slow when querying by XPath. Painfully, unusable slow.

Wow, that is an interesting find.
In last half a year I was able to convince and implement usage of FlaUI in our Testing department. I think it got pretty successfull. But after 4 months I found out about WinAppDriver and though if I didn't make a mistake. But this reassured me that I did not. WinAppDriver is nice way of doing UI Test automation, but I still think it is not ready.

We are also doing some UI performance tests with FlaUI and it has been pretty consistent and fast. Although FlaUI is not perfect. 

We had to create a lot of extensions for it to be reliable. There is ton of missing features that doesn't have Retry mechanisms in FlaUI. If anyone is interested I could make these extensions public (even just for FlaUI developers as a feedback on FlaUI from our bussiness perspective)

**Comment by miloszkukla** [comment]
@jakubsuchybio It would be very interesting to see these extensions of your on GitHub - some it could probably make it way to FlaUI if they are general enough, so if you can please share it :)

The interesting point about FlaUI - even though it may not be perfect (PRs are welcome I believe) - is that it is the only open-source and maintained UIAv3 wrapper I'm aware of and it has ton of features that we would need to implemented on top of UIAutomation by ourselves.

@daluu I don't think there would any substantial difference between these two you mentioned becuase from what I've seen, the UIAutomation calls the ones that take most of the time. There is substantial difference in execution time between UIAv2 and UIAv3 though (UIAv3 being much faster).

**Comment by Roemer** [comment]
@jakubsuchybio Yes I would be interested in those changes. I haven't spent much time in FlaUI lately but plan on doing some improvements, for example .net standard support.

**Comment by jakubsuchybio** [comment]
@Roemer Alright :) here it is: https://github.com/jakubsuchybio/FlaUI.TestUtils
Most notable extension are:
```csharp
AutomationElement FindFirstDescendant(this AutomationElement element, Func<ConditionFactory, ConditionBase> conditionFunc, TimeSpan timeout, bool nothrow = false)
void WaitUntilEnabled(this AutomationElement element, TimeSpan timeout)
Process WaitForStart(string path, TimeSpan timeout, bool throwOnTimeout = true)
void WaitUntilExited(this Process process, TimeSpan timeout, bool forceKill = false)
WaitEx: void UntilResponsive(AutomationElement element, TimeSpan timeout)
Window GetModalWindow(this Window window, Func<Window, bool> condition, TimeSpan timeout)
```
There are some more which are not so general and some that are not general at all, just shortcuts for our paper cuts. For example clicking inside .msi installer package is so anoying, because everytime you click, it creates new window. Etc.

**Comment by maxinfet** [comment]
I personally need the performance that building directly on top of UIAv2 and UIAv3 gives. We use UIA to gauge whether our application has gotten slower. I am not using FlaUI but I am pushing for my company to adopt it because I see no reason for us to build our own UIAv3 wrapper. 

If people do intend to use the WinAppDriver and need retry functionality I have pulled the retry functionality out into its own library which I use with the managed UIAv2 wrapper https://github.com/maxinfet/Mulligan.

**Comment by Roemer** [comment]
I think there is nothing to add here currently. Feel free to reopen otherwise.

**Comment by polantest** [comment]
Hi guys, does anyone have an update on the matter? Have things changed during last few years? I am facing a decision of which tool should we use in our project for testing .NET desktop application.

**Comment by jakubsuchybio** [comment]
At our business we still stick with FlaUI. WinAppDriver to my knowledge is another dead project of MSFT.
But nowadays they are pushing MAUI apps and I don't know how they do ui testing there.
