### ISSUE TITLE
KeyBoard and mouse can not use in the same time

### ISSUE THREAD

**Issue by wxue1011** [Roemer/FlaUI#251]
I used Ctrl Pressing with mouse drag. It just liked Ctrl not pressing.
I appreciate your help. Thanks a lot.

**Comment by yawnston** [comment]
It would be helpful if we had a code sample. Did your code look something like this? 

```cs
Mouse.Position = new Point(10, 10);
Keyboard.Press(VirtualKeyShort.CONTROL);
Mouse.Down(MouseButton.Left);
Mouse.MoveBy(100, 100);
Mouse.Up(MouseButton.Left);
Keyboard.Release(VirtualKeyShort.CONTROL);
```

**Comment by wxue1011** [comment]
It like below. It seemed Control key not be pressed. Thanks.

```
Mouse.Down(MouseButton.Left);
Keyboard.Pressing(FlaUI.Core.WindowsAPI.VirtualKeyShort.CONTROL);
Mouse.Drag(MouseButton.Left, p, 0, -50);
Keyboard.Release(FlaUI.Core.WindowsAPI.VirtualKeyShort.CONTROL);
```

**Comment by yawnston** [comment]
So for one, `Keyboard.Pressing` returns IDisposable (it releases the specified key when the object is disposed), so either use `Keyboard.Press` instead, or release the key by disposing the IDisposable. But that's not the issue you're having.

If I understand correctly, you just want to press Control and then drag something? I'm not sure what the purpose of the first line (the `Mouse.Down`) is. If I had to guess then the reason the Control isn't registering is because the mouse button is already being held down when the key is pressed. Try the mouse drag like this (without the `Mouse.Down` first):

```cs
Keyboard.Press(FlaUI.Core.WindowsAPI.VirtualKeyShort.CONTROL);
Mouse.Drag(MouseButton.Left, p, 0, -50);
Keyboard.Release(FlaUI.Core.WindowsAPI.VirtualKeyShort.CONTROL);
```

Of course I don't have the context, so if the first `Mouse.Down` was meant to interact with some UI element before the drag, then you should make sure you release the mouse button (using `Mouse.LeftClick` instead of `Mouse.Down`) before you press Control and drag.

**Comment by wxue1011** [comment]
I tried Keyboard.Press that also made no sense.
And i also tried without Mouse.Down, still like Control key not be pressed.
Thanks anyway.

**Comment by Roemer** [comment]
Are you sure it is not working?
I just tried
```csharp
Keyboard.Press(FlaUI.Core.WindowsAPI.VirtualKeyShort.SHIFT);
Mouse.Drag(MouseButton.Left, Mouse.Position, 50, 0);
Keyboard.Release(FlaUI.Core.WindowsAPI.VirtualKeyShort.SHIFT);
```
which actually selects 50 pixels of text to the right of the current mouse position.

**Comment by Roemer** [comment]
As all tests succeeded, I will close this. Feel free to re-open if you still have issues with it.
