### ISSUE TITLE
Problem with IsOffscreen property of first item of WPF ComboBox

### ISSUE THREAD

**Issue by pavBernat** [Roemer/FlaUI#253]
Hi, 
there seems to be something weird going on with the IsOffscreen property of items in normal WPF ComboBox. It seems that when no items are selected, the first item has IsOffscreen property set to true, but all the rest have it set to false. i don't think that is correct.

You can test this by adding following test to ComboBoxTests.cs:
```
[Test]
[TestCase(0)]
[TestCase(1)]
[TestCase(2)]
[TestCase(3)]
public void ComboBoxItemsIsOffscreen(int comboBoxItem)
{
    var combo = _mainWindow.FindFirstDescendant(cf => cf.ByAutomationId("NonEditableCombo")).AsComboBox();
    var isOffscreen = combo.Items[comboBoxItem].IsOffscreen;
    Assert.IsFalse(isOffscreen);
}
```

**Comment by Roemer** [comment]
Hi @pavBernat 
The problem seems to be that there usually is an opening animation during which the items are offscreen. If you manually expand the combo `combo.Expand()` and add a small delay (100ms) afterwards, the test will run correctly.
I tried with a spinner to wait until the state is `ExpandCollapseState.Expanded` but it seems that this state is set before the animation is finished...
The only working workaround was to add a sleep or wait until the first item is on-screen:
```csharp
SpinWait.SpinUntil(() =>
{
    return combo.Items[0].IsOffscreen == false;
});
```
which of course only works if there are items in the combo box.
I have now added a property `AnimationDuration` on the ComboBox (default 100ms) which can be used to control how long it should wait after expanding/collapsing.
This should solve the issue and allows enough flexibility to adjust the value. Feel free to re-open if there are still issues.
