### ISSUE TITLE
I can not run a single test:(

### ISSUE THREAD

**Issue by vvidov** [Roemer/FlaUI#270]
I can not run a single test:(

**Comment by Roemer** [comment]
That's not a lot of info. Please describe in detail what issues you have.

**Comment by vvidov** [comment]
just tests do not run. but I added nunit and nunitadapter and it works now. one more question, how can run test on build server without desktop session

**Comment by kevinheyvaert** [comment]
I think you can't. You need an active desktop session to run the tests (from experience in my case). I run my build server (TeamCity, started from the cmd (otherwise it will not work, see https://teamcity-support.jetbrains.com/hc/en-us/community/posts/206261739-Running-Automated-GUI-tests-with-TeamCity )) with a desktop session that will never locking the screen. If the screen is locked, then the tests will also not run.

**Comment by Roemer** [comment]
You cannot run them without a desktop session. Otherwise there is nothing that can be displayed or interacted with and they will always fail.

**Comment by Roemer** [comment]
Closed as it is working and the question is answered.
