### ISSUE TITLE
Where can I get help from a document?

### ISSUE THREAD

**Issue by ohacn** [Roemer/FlaUI#32]
Where can I get help from a document?
Thanks!

**Comment by Roemer** [comment]
What do you mean by document? And what do you mean by help? A little bit more information would be good.

**Comment by ohacn** [comment]
I mean to say that there are no help documentation or examples.
English is not very good, do not mind

**Comment by Roemer** [comment]
Ah. First there are some information in the wiki (https://github.com/Roemer/FlaUI/wiki). Feel free to extend it. Other there is a lot of "sample code" in the UI-Tests project (you find these in the folder src/FlaUI.Core.UITests). Hope this helps a little. Otherwise post your concrete questions here.

**Comment by ohacn** [comment]
Thank you, man. You're a good man.
