### ISSUE TITLE
How click to control without mouse moving?

### ISSUE THREAD

**Issue by Radzhab** [Roemer/FlaUI#35]
I use demo code from wiki. All work, but my mouse) Its manually moving it. I think this library use winapi and its can click on button without mouse moving...

**Comment by Roemer** [comment]
There are multiple aspects here:
1. There is a boolean to define if the mouse should move slowly or instantly
2. If you use the mouse clicks the mouse always need to be at the position that should be clicked. There is no way around.
3. Maybe it us better if you use Invoke from the InvokePattern.

**Comment by Roemer** [comment]
You can use WinAPI with SendMessage to fake clicks but then you could miss some events like mouse enter and such. I might think to add that as well but in general using patterns is better.

**Comment by Radzhab** [comment]
@Roemer  why you think that i miss mouse enter event?

**Comment by Roemer** [comment]
Because this one is only fired when the mouse effectively moves over an element.

**Comment by Roemer** [comment]
I did some more research (again) and the SendMessage method is very unreliable (see https://blogs.msdn.microsoft.com/oldnewthing/20050530-11/?p=35513). And the SendInput method (which is the best to simulate the mouse) does not allow to "send" to other windows than the foreground window.
If you need to click a button without moving the mouse, use the invoke method from the invoke pattern. If the element you want to click does not support the invoke pattern, use your own SendMessage for this and hope that it works. Since it's unreliable, I will not add this to the FlaUI base framework. Feel free to add more comments if you still have questions.
