### ISSUE TITLE
Missing classes like AutomationElementCollection, AutomationElementIdentifiers

### ISSUE THREAD

**Issue by JinendraG** [Roemer/FlaUI#38]
I am planning to upgrade from UIAComwrapper to Fla UI. But seems Fla UI is missing few of the classes I am currently using with an old library like AutomationElementCollection, AutomationElementIdentifiers.

Please confirm if this is an issue or I am missing some configuration

**Comment by Roemer** [comment]
Great to hear you're trying to upgrade!
Regarding your question:

All methods that return a "collection" of AutomationElements return an array of AutomationElements so you're free to convert them to a list or whatever you need so I do not see a need for a specific AutomationElementCollection.

The ElementIdentifiers are either inside the patterns or the element itself.
So to get the property identifiers for the grid item you can use
```Automation.PropertyLibrary.GridItem``` or even ```element.PatternFactory.GetGridItemPattern().Properties```.
Same for events (EventLibrary) or even Patterns (PatternLibrary).
The element properties (which do not belong to a pattern) ar in PropertyLibrary.Element or even in an element itself with ```element.Properties.AcceleratorKeyProperty```

In general, you should not need to use and of the elementidentifiers since everything is implemented in the patterns directly.

Does this answer your question?
