### ISSUE TITLE
Add(ByIndex(0))

### ISSUE THREAD

**Issue by sean-sel** [Roemer/FlaUI#56]
I'm investigating using FLaUI instead of White and was looking for the equivalent of AndIndex in White

For Example in White I have
 mainWindow.Get<TextBox>(SearchCriteria.ByControlType(ControlType.Edit).AndIndex(2));

What's the equivalent in FLaUI to the above line, to use And.Index(2)?

**Comment by Roemer** [comment]
The .Index is not supported by the underlying technology (MS UIA) and therefore gives the wrong impression, that this might be efficient. That's why I currently do not support the Index directly.
You can of curse use the following:
```csharp
mainWindow.FindAllDescendants(cf=>cf.ByControlType(ControlType.Edit))[2];
```
That would be exactly what White does. Another approach would be to use XPath which "can" be more efficient if you use a lot of indexers:
```csharp
mainWindow.FindFirstByXPath("(//Edit)[2]");
```

**Comment by Roemer** [comment]
Does this answer your question and can it be closed?
